### ISSUE TITLE
testing finished?  Also, 1N4148 diode.

### ISSUE THREAD

**Issue by WhiteHare** [hallard/WeMos-RFM69#1]
Your introductory post says, "Boards arrived from OSHPark, I did not fully tested them yet, I will update ASAP. Use at your own risks."

Have you had a chance to finish testing it yet, and if so, what were the results?

Also, specifically which SMD 1N4148 part do you recommend using?   Is it there entirely for polarity protection, such that simply shorting jumper J4 can be "good enough" without missing anything else?

BTW, I  like that you silkscreened the component values directly onto the board.  Also using the  two WS2812B's is a nice touch.

**Comment by hallard** [comment]
@WhiteHare 
thanks for the comment, I didn't had time to test them but I assembled one.
There is one error on the silkscreen for the module, they are reversed, IE 
RFM69W and RFM69HW is for RFM12B and RFM69CW and vice-versa, please check with module pinout before soldering.
1N4148 diode is for level voltage of WS2812B decreasing 1st led to 4.3V (see this [post](http://www.electrobob.com/ws2812-level-translator/)) but It should works out of the box without any problem, depending on WS2812 type. In this case JP4 need to be closed.

**Comment by hallard** [comment]
Tested with RFM69HW with 2 WS2812B RGBW LEDS, works fine, done a 1.0a release
- Correct RFM module silkscreen reversed
- New SMA-UFL connector
