### ISSUE TITLE
Are LEDs required for the shield to work?

### ISSUE THREAD

**Issue by phretor** [hallard/WeMos-RFM69#3]

**Comment by hallard** [comment]
Nop, Led can be driven by firmware if it's implemented, but leaving without then will not hurt anything, so the 2 I2C resistors if you don't have any 2IC devices.

**Comment by phretor** [comment]
Wait, I don't understand. Are you saying I should *not* put any I2C resistors if I'm *not* using the LEDs?

Have you tested this shield with MySensors by any chance?

**Comment by hallard** [comment]
No, sorry just saying:

- Led are optionals
- I2C pullup optionals if you're not using I2C devices

No relation between both

Sorry not tested with mySensors, to be honest I've done this 5 years ago, don't remember everything, I'm not using it anymore.
